package com.sample.rules

import com.model.lts.Transition;
import com.utils.stringCleaner;
import com.main.Main;

/*rule "modify a transition"
 	when
    $t : Transition( label == "?/json.htm" )//conditions
    then
    System.out.println("transition exists: " + $t.toString());
   	$t.setName($t.getName() + "boo");
end*/

rule "begin"
	when 
	$t : Transition(source.isInit() == true)
	then
	//System.out.println("begin");
	$t.addParameter("begin=TRUE");
end

rule "end"
	when 
	$t : Transition(target.isInit() == true)
	then
	//System.out.println("end");
	$t.addParameter("end=TRUE");
end

rule "getUpdate"
	when
	$t1 : Transition(!isInput(), contain("get-update", "get_update") )
	$t2 : Transition(isInput(), contain("data"), getSource() == $t1.getTarget())
	then
	//System.out.println("getUpdate");
	$t2.addParameter("getUpdate_" + stringCleaner.clean($t2.getUpdate()) + "=TRUE");
	//System.out.println("you can write code in the drool file");
	Main.keyWords.get("getUpdate_d").addValue(stringCleaner.clean($t2.getUpdate()));
end

rule "encrypted" 
	when
	$t : Transition(isEncrypted())
	then
	$t.addParameter("encrypted=TRUE");
end 

/*rule "signature" TODO but how?
	when
	
	then
	
end */

/*rule "searchUpdate"
	when
	$t : Transition(isReq() == true, isInput() == false, contain("update", "findUpdate", "get_update"))
	then
	//System.out.println("searchUpdate");
	$t.addParameter("searchUpdate=TRUE");
end*/

rule "searchUpdate"
	when
	$t : Transition(isReq() == true, isInput() == false, !contain2("updatefile", "findUpdate", "get_update").isEmpty())
	then
	//System.out.println("searchUpdate");
	for (String param: $t.contain2("update", "findUpdate", "get_update")){
		$t.addParameter("searchUpdate_"+ stringCleaner.clean(param) + "=TRUE");
		Main.keyWords.get("searchUpdate_d").addValue(stringCleaner.clean(param));
	}
end

rule "login" //TODO abstraire en une seule transition
	when
	$t1 : Transition(isReq() == true, contain("login", "user", "username"))
	$t2 : Transition(isReq() == false, isOk() == true, getSource() == $t1.getTarget())
	$t3 : Transition(isReq() == true, contain("password", "pass", "pwd"), getSource() == $t2.getTarget())
	then
	//System.out.println("login");
	$t1.addParameter("loginAttempt_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	$t2.addParameter("loginAttempt_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	$t3.addParameter("loginAttempt_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginAttempt_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end

rule "login2"
	when
	$t : Transition(isReq() == true, contain("login", "user", "username"), contain("password", "pass", "pwd"))
	then
	//System.out.println("blogin2");
	$t.addParameter("loginAttempt_" + stringCleaner.clean($t.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginAttempt_c").addValue(stringCleaner.clean($t.getOtherCompo()));
end

rule "login3"
	when
	$t1 : Transition(isReq() == true, contain("login", "user"))
	$t2 : Transition(isReq() == false, isOk() == false, getSource() == $t1.getTarget()) 
	then
	//System.out.println("login3");
	$t1.addParameter("loginAttempt_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginAttempt_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end

rule "logintls"
	when
	$t1 : Transition(isReq() == true, contain("Client Hello"))
	$t2 : Transition(isReq() == false, getSource() == $t1.getTarget(), contain("Server Hello")) 
	$t3 : Transition(isReq() == true, getSource() == $t2.getTarget(), contain("Encrypted Handshake Message")) 
	$t4 : Transition(isReq() == false, getSource() == $t3.getTarget(), contain("Encrypted Handshake Message")) 
	then
	//System.out.println("logintls");
	$t1.addParameter("loginAttempt_" + stringCleaner.clean($t4.getOtherCompo()) + "=TRUE");
	$t2.addParameter("loginAttempt_" + stringCleaner.clean($t4.getOtherCompo()) + "=TRUE");
	$t3.addParameter("loginAttempt_" + stringCleaner.clean($t4.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginAttempt_c").addValue(stringCleaner.clean($t4.getOtherCompo()));
	$t4.addParameter("authenticated_" + stringCleaner.clean($t4.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("authenticated_c").addValue(stringCleaner.clean($t4.getOtherCompo()));
end

rule "authMega"
	when
	$t1 : Transition(isReq() == true, contain("Credentials:"), !contain("Referer:"))
	$t2 : Transition(isReq() == false, isOk() == true, getSource() == $t1.getTarget())
	then
	//System.out.println("authmega");
	$t1.addParameter("loginAttempt_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginAttempt_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
	$t2.addParameter("authenticated_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("authenticated_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end

rule "loginfailMega"
	when
	$t1 : Transition(isReq() == true, contain("Credentials:"), !contain("Referer:"))
	$t2 : Transition(isReq() == false, isOk() == false, getSource() == $t1.getTarget())
	then
	//System.out.println("loginfailmega");
	$t1.addParameter("loginAttempt_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginAttempt_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
	$t2.addParameter("loginFail_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginFail_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end

rule "authenticated"  
	when
	$t1 : Transition(isReq() == true, contain("password", "pass", "pwd"))
	$t2 : Transition(isReq() == false, isOk() == true, getSource() == $t1.getTarget()) 
	then
	//System.out.println("authneticatesd");
	$t2.addParameter("authenticated_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("authenticated_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end 

rule "loginFail"
	when
	($t1 : Transition(isReq() == true, contain("login", "user"))
	or
	$t1 : Transition(isReq() == true, contain("password", "pass", "pwd")))
	$t2 : Transition(isReq() == false, isOk() == false, getSource() == $t1.getTarget()) 
	then
	//System.out.println("loginFail");
	$t2.addParameter("loginFail_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("loginFail_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end

rule "lockout"
	when
	$t1 : Transition(isReq() == true, contain("password", "pass", "pwd"))
	$t2 : Transition(isReq() == false, isOk() == false, getSource() == $t1.getTarget(), contain("locked", "account locked", "lockout")) 
	then
	//System.out.println("lockout");
	$t2.addParameter("lockout_" + stringCleaner.clean($t2.getOtherCompo()) + "=TRUE");
	Main.keyWords.get("lockout_c").addValue(stringCleaner.clean($t2.getOtherCompo()));
end

rule "passwordRecovery" 
	when
	$t : Transition(isReq() == true, isInput() == true, contain("forgotten password", "password recovery", "forget"))
	then
	//System.out.println("poassword recovery");
	$t.addParameter("passwordRecovery=TRUE");
end

/*rule "blackListedWords" ////
	when
	$t : Transition(!blackListed().isEmpty())
	then
	for (String param: $t.blackListed()){
		$t.addParameter("blackListedWord_" + stringCleaner.clean(param) + "=TRUE");
		Main.keyWords.get("blackListedWord_d").addValue(stringCleaner.clean(param));
	}
end
*/
rule "blackListedWords" 
	when
	$t : Transition(!blackListed().isEmpty())
	then
	$t.addParameter("blackListedWords=TRUE");
end
rule "input"
	when
	$t : Transition(isInput())
	then
	//System.out.println("input");
	$t.addParameter("input=TRUE");
end

rule "output"
	when
	$t : Transition(!isInput())
	then
	//System.out.println("output");
	$t.addParameter("output=TRUE");
end

rule "errorResponse" 
	when
	$t : Transition(isReq() == false, isOk() == false)
	then
	//System.out.println("errorrespo");
	$t.addParameter("errorResponse=TRUE");
end 

rule "XSS"  //////
	when
	$t : Transition(isReq(), !containXSS().isEmpty)
	then
	for (String param: $t.containXSS()){
		$t.addParameter("XSS_" + stringCleaner.clean(param) + "=TRUE");
		Main.keyWords.get("XSS_d").addValue(stringCleaner.clean(param));
	}
end

rule "sensitive"
	when
	$t : Transition(!sensitive().isEmpty())
	then
	for (String param: $t.sensitive()){
		$t.addParameter("sensitive_" + stringCleaner.clean(param) + "=TRUE");
		Main.keyWords.get("sensitive_d").addValue(stringCleaner.clean(param));
	}
end

rule "cmdSearchUpdate"
	when
	$t : Transition(isReq() == true, isInput(), contain("command", "cmd", "order"), contain("searchUpdate", "search_update"))
	then
	//System.out.println("cmdsearchup");
	$t.addParameter("cmdSearchUpdate=TRUE");
end


rule "Request"
	when
	$t : Transition(isReq() == true)
	then 
	//System.out.println("req");
	$t.addParameter("request=TRUE");
end

rule "Response"
	when
	$t : Transition(isReq() == false)
	then 
	//System.out.println("resp");
	$t.addParameter("response=TRUE");
end

	
rule "SQLinj"
	when
	$t : Transition(isReq() == true, containSQL() == true)
	then
	//System.out.println("sqlinj");
	$t.addParameter("SQLinjection=TRUE");
end

rule "Unavailable"
	when
	$t : Transition(isReq() == false, contain("504", "time-out"))
	then
	$t.addParameter("unavailable=TRUE");
end

rule "Credential"
	when
	$t : Transition(!contain2("Credential", "login", "password").isEmpty())
	then
	for (String param: $t.contain2("Credential", "login", "password")){
		$t.addParameter("credential_" + stringCleaner.clean(param) + "=TRUE");
		Main.keyWords.get("credential_d").addValue(stringCleaner.clean(param));
	}
end

/* not needed 
rule "from"
	when
	
	then
	
end

rule "to"
	when
	
	then
	
end*/
